# Generated by Django 3.2.9 on 2021-11-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
