# Generated by Django 3.2.9 on 2021-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bookmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='age_group',
            field=models.CharField(choices=[('CHILD', 'child'), ('YOUNG ADULTS', 'young adults'), ('MIDDLE-AGED ADULTS', 'middle-aged adults'), ('OLD-AGED ADULTS', 'old-aged adults')], max_length=20),
        ),
    ]
