# Generated by Django 3.2.9 on 2021-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shopbasketmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=24),
        ),
    ]
