# Generated by Django 3.2.9 on 2021-11-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_ordermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Prepayment', 'prepayment'), ('Inprocess', 'inprocess'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], max_length=12, null=True),
        ),
    ]
