# Generated by Django 3.2.9 on 2021-11-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211117_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Prepayment', 'prepayment'), ('Inprocess', 'inprocess'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], default='Prepayment', max_length=12, null=True),
        ),
    ]
